packages:
  - packages/*
  - configs/*

catalog:
  '@eslint/js': '^9.9.0'
  '@radix-ui/themes': '^3.1.3'
  '@stitches/react': '^1.2.8'
  '@storybook/addon-essentials': '^8.2.9'
  '@storybook/addon-interactions': '^8.2.9'
  '@storybook/addon-links': '^8.2.9'
  '@storybook/addon-themes': '^8.2.9'
  '@storybook/blocks': '^8.2.9'
  '@storybook/react-vite': '^8.2.9'
  '@storybook/react': '^8.2.9'
  '@storybook/test': '^8.2.9'
  '@tanstack/react-query': '^4.18.0'
  '@testing-library/dom': '^10.4.0'
  '@testing-library/react': '^16.0.1'
  '@trpc/client': '^10.45.2'
  '@trpc/react-query': '^10.45.2'
  '@trpc/server': '^10.45.2'
  '@types/react-dom': '^18.3.0'
  '@types/react': '^18.3.3'
  '@vitejs/plugin-react-swc': '^3.5.0'
  'dotenv': '^16.4.5'
  'eslint-config-prettier': '^9.1.0'
  'eslint-plugin-react-hooks': '^5.1.0-rc.0'
  'eslint-plugin-react-refresh': '^0.4.9'
  'eslint-plugin-react': '^7.36.1'
  'eslint-plugin-turbo': '^2.1.2'
  'eslint': '^9.9.0'
  'globals': '^15.9.0'
  'husky': '^9.1.5'
  'jsdom': '^25.0.0'
  'lint-staged': '^15.2.10'
  'prettier': '^3.3.3'
  'react-dom': '^18.3.1'
  'react': '^18.3.1'
  'storybook': '^8.2.9'
  'superjson': '^2.2.1'
  'turbo': '^2.1.2'
  'typescript-eslint': '^8.5.0'
  'typescript': '^5.6.2'
  'vite': '^5.4.1'
  'vitest': '^2.0.5'
  'zod': '^3.23.8'
